### PR TITLE
Use rules from new.yaml by default

### PR DESCRIPTION
**Pull request by Anatolay**
A temporary hack to use new rules in `eo-phi-normalizer rewrite` by default.

Will be removed once built-ins are updated.

### CODE REVIEW

**Review by deemp — APPROVED** [review]
LGTM

**Comment by deemp** [comment]
@Anatolay, hmm, not really good. If one uses normalizer as a standalone program outside of the repo, the normalizer won't find `new.yaml`. So, you should `embedFile` like this:

https://github.com/objectionary/eo-phi-normalizer/blob/9ba4e2c9edb3ac5b937584d55c13df682c4a251c/eo-phi-normalizer/src/Language/EO/Phi/Report/Html.hs#L66

**Comment by 0crat** [comment]
@Anatolay Hello team member, I noticed that your branch name "`hack-new-rules`" doesn't follow our naming convention. As per our [policy](https://www.yegor256.com/2014/04/15/github-guidelines.html), branch names should match the ticket number you're working on. For example, "`554`" would be an ideal name in this case. Due to this, there's a deduction of 12 points. Your current balance is now [-8](https://www.eolang.org/zerocracy/objectionary-vitals.html). Let's ensure we stick to the convention moving forward to maintain consistency in our project management. Keep up the good work!

**Comment by 0crat** [comment]
@Anatolay Great work on your contribution! 🌟 You've earned +4 points: +4 base, -8 for exceeding hits-of-code (250 >= 200), -4 for minimal comments, +12 bonus. [Keep up](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the momentum! Your current balance is [-20](https://www.eolang.org/zerocracy/objectionary-vitals.html). Looking forward to your next submission!

**Pull request merged**
