### PR TITLE
607 update eo to 0.49.4

### LINKED ISSUE #607: Update eo to 0.46.0
## Details

The EO `0.46.0` is available (https://github.com/objectionary/eo/releases/tag/0.46.0).

## Subtasks

- [ ] Update the `eo` submodule to the `0.46.0` tag
- [ ] Find out which home tag should be used. Currently, `0.41.1` is used https://github.com/objectionary/eo-phi-normalizer/blob/d80d8b9abe4a3b796d34cdba4ca40af7453a2088/scripts/lib.sh#L186

### PR DESCRIPTION
**Pull request by deemp**
- Closes #607

Changes:
- Implemented parsing and printing syntax sugar for EO 0.49.4

### CODE REVIEW

**Comment by deemp** [comment]
@yegor256, for some reason, the pipeline fails

https://github.com/objectionary/eo-phi-normalizer/actions/runs/12360133696/job/34494382837#step:12:288

Environment:

`eolang`: `0.28.0`

Commands:

```
cat org/eolang/bool-tests.eo
```

```
+package org.eolang
+tests

# No comments.
[] > compares-two-bools
  Q
  .org
  .eolang
  .true
  .eq > @
    Q
    .org
    .eolang
    .true:0

# No comments.
[] > compares-two-different-types
  Q
  .org
  .eolang
  .true
  .eq
    42:0
  .not > @

# No comments.
[] > compares-bool-to-bytes
  Q
  .org
  .eolang
  .true
  .eq
    01-:0
  .and > @
    Q
    .org
    .eolang
    .false
    .eq:0
      00-:0

# No comments.
[] > compares-bool-to-string
  Q
  .org
  .eolang
  .true
  .eq
    "\u0001":0
  .and > @
    Q
    .org
    .eolang
    .false
    .eq:0
      "\u0000":0

# No comments.
[] > compares-bool-to-bytes-reverse
  01-
  .as-bytes
  .eq
    Q
    .org
    .eolang
    .true:0
  .and > @
    00-
    .as-bytes
    .eq:0
      Q
      .org
      .eolang
      .false:0
```

```
eoc test
```

```
EO objects registered in .eoc/eo-foreign.json
EO program assembled in .eoc
[ERROR] In 61 XMIR files, we found 168 warnings
[ERROR] Failed to execute goal org.eolang:eo-maven-plugin:0.49.1:lint (default-cli) on project eoc: 'LintMojo' execution failed: java.lang.IllegalStateException: In 61 XMIR files, we found 168 warnings -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
The command "/home/eyjafjallajokull/Desktop/gh/normalizer/node_modules/eolang/mvnw/mvnw eo:lint -Deo.version=0.49.1 -Deo.tag=0.49.1 --quiet -Deo.sourcesDir=/home/eyjafjallajokull/Desktop/gh/normalizer/tmp/upgrade -Deo.targetDir=/home/eyjafjallajokull/Desktop/gh/normalizer/tmp/upgrade/.eoc -Deo.outputDir=/home/eyjafjallajokull/Desktop/gh/normalizer/tmp/upgrade/.eoc/classes -Deo.generatedDir=/home/eyjafjallajokull/Desktop/gh/normalizer/tmp/upgrade/.eoc/generated-sources -Deo.placed=/home/eyjafjallajokull/Desktop/gh/normalizer/tmp/upgrade/.eoc/eo-placed.csv -Deo.placedFormat=csv -Deo.failOnWarning=true --batch-mode --color=never --update-snapshots --fail-fast --strict-checksums" exited with #1 code
```

**Comment by yegor256** [comment]
@deemp use `--easy` option for `eoc`

**Comment by deemp** [comment]
@fizruk, the pipeline fails because the syntax sugar as mentioned in #603 hasn't yet been implemented.

https://github.com/objectionary/eo-phi-normalizer/actions/runs/12367097278/job/34514834809?pr=617#step:12:514

**Comment by deemp** [comment]
@yegor256, should `Φ̇.true.eq(Φ̇.true)` be desugared as `Φ.org.eolang.true.eq(α0 ↦ Φ.org.eolang.true)`?

image

**Comment by yegor256** [comment]
@deemp yes, exactly

**Comment by deemp** [comment]
@fizruk, dataization of the celsius example produces bytes for some reason.

```
cat tmp/foo.phi
```

```
{⟦
    c ↦ Φ.org.eolang.number(
        as-bytes ↦ Φ̇.bytes(Δ ⤍ 40-39-00-00-00-00-00-00)
    ), // 25.0
    φ ↦ ξ.c.times(x ↦ ⟦ Δ ⤍ 3F-FC-CC-CC-CC-CC-CC-CD ⟧)  // 1.8
            .plus(x ↦ ⟦ Δ ⤍ 40-40-00-00-00-00-00-00 ⟧), // 32.0
⟧}
```

```
eo-phi-normalizer dataize --recursive -d eo-phi-normalizer/data/0.41.2/org/eolang/number.phi -d eo-phi-normalizer/data/0.41.2/org/eolang/bytes.phi tmp/foo.phi
```

````
40-53-40-00-00-00-00-00
```

**Comment by deemp** [comment]
@fizruk, @yegor256, I tried to implement the syntactic sugar for such expressions

```
⟦ number(as-bytes) ↦ ⟦ ... ⟧ ⟧
```

but then got shift-reduce conflicts.

I had the following definitions in the [Syntax.cf](https://github.com/objectionary/eo-phi-normalizer/blob/eb8ca60c0cd7c22d1e7c0389b447675c054e9fef/eo-phi-normalizer/grammar/EO/Phi/Syntax.cf).

```
Label.      Attribute ::= LabelId ;
...
AttrSugar.  Attribute ::= LabelId "(" [LabelId] ")";
```

I think when parser encounters `number` it doesn't know whether it should reduce it to an `Attribute` or shift and put `(` on the parser stack.

**Comment by yegor256** [comment]
@deemp I'm not sure I understand what's the source of the shift-reduce conflict:

> I think when parser encounters number it doesn't know whether it should reduce it to an Attribute or shift and put "(" on the parser stack.

This text is not clear for me. Can you elaborate a bit further?

**Comment by yegor256** [comment]
@deemp BTW, this EBNF we use to parse phi expressions, maybe will help: https://camo.githubusercontent.com/77e1ebd2a73dbe1889a630de643778e76b81b406bf1bdae75be8f833ac67f791/68747470733a2f2f7777772e656f6c616e672e6f72672f65626e662f5068692e706e67

**Comment by deemp** [comment]
> This text is not clear for me. Can you elaborate a bit further?

@yegor256, you use ANTLR which generates top-down (LL) parsers. We use BNFC which generates bottom-up (LR) parsers. We use BNFC for convenience.

A GLR parser could try multiple options.
1. Parse `number` from `⟦ number(as-bytes) ↦ ⟦ ... ⟧ ⟧` as a `LabelId` (reduce).
2. Parse `number`, then parse `(as-bytes)` from `⟦ number(as-bytes) ↦ ⟦ ... ⟧ ⟧` (shift), then combine them into `AttrSugar`.

However, currently, BNFC-generated parser (using the `--glr` flag) don't typecheck. 

Hence, we have to use a LR parser which can't try multiple options and thus gets a shift/reduce conflict.

@fizruk, please correct me if I'm wrong.

I see the following options:
- (Simple) (Temporarily) Make the $\varphi$-calculus syntax unambiguous for a LR parser (see my suggestion about the syntax https://github.com/objectionary/eo-phi-normalizer/pull/617#issuecomment-2555665911).
- (Hard) Use `happy` and `alex` to generate parsers more flexibly and probably get a working GLR parser.
- (Hard) Rewrite the parser using a parser combinator library.

**Comment by yegor256** [comment]
@deemp will it help if we change our grammar such that attribute name in `⟦ a(x) ↦ ⟦ ... ⟧ ⟧` expression will always be followed by brackets, even if the list inside them is empty?

```
⟦ a() ↦ ⟦ ... ⟧ ⟧
⟦ a(x) ↦ ⟦ ... ⟧ ⟧
⟦ a(x, y) ↦ ⟦ ... ⟧ ⟧
```

**Comment by deemp** [comment]
@fizruk, do you have an idea why these errors occur?

https://github.com/objectionary/eo-phi-normalizer/actions/runs/12482015734/job/34835445072#step:5:343

**Comment by deemp** [comment]
@fizruk, some dataization tests still fail. Please check.

https://github.com/objectionary/eo-phi-normalizer/actions/runs/12505740341/job/34889571481?pr=617#step:5:338

**Pull request merged**
